// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3WdlHI3CdEQ-Ss_3iIiKwwKnr7TglDdI',
    appId: '1:682305739300:web:dd312929dfe00348d756b1',
    messagingSenderId: '682305739300',
    projectId: 'careercoach-63e7e',
    authDomain: 'careercoach-63e7e.firebaseapp.com',
    storageBucket: 'careercoach-63e7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXe5Stg6yWYfl5xI2zIv2ETMg44YEChI',
    appId: '1:682305739300:android:ffc8a9ec8d03349dd756b1',
    messagingSenderId: '682305739300',
    projectId: 'careercoach-63e7e',
    storageBucket: 'careercoach-63e7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHj2PJnUvfqgQWuHCX2v84T4fN0k-DxrQ',
    appId: '1:682305739300:ios:619e76f2ae133774d756b1',
    messagingSenderId: '682305739300',
    projectId: 'careercoach-63e7e',
    storageBucket: 'careercoach-63e7e.appspot.com',
    iosBundleId: 'com.eparivartan.careercoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHj2PJnUvfqgQWuHCX2v84T4fN0k-DxrQ',
    appId: '1:682305739300:ios:619e76f2ae133774d756b1',
    messagingSenderId: '682305739300',
    projectId: 'careercoach-63e7e',
    storageBucket: 'careercoach-63e7e.appspot.com',
    iosBundleId: 'com.eparivartan.careercoach',
  );
}
